spring:
  application:
    name: airBnbApp
  datasource:
    url: jdbc:postgresql://localhost:5432/airBnb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
